package com.route.islami.Fragments

import com.route.islami.Chapter

object AppConstants {
    val arabicSuraName: List<String> = listOf(
        "الفاتحه",
        "البقرة",
        "آل عمران",
        "النساء",
        "المائدة",
        "الأنعام",
        "الأعراف",
        "الأنفال",
        "التوبة",
        "يونس",
        "هود",
        "يوسف",
        "الرعد",
        "إبراهيم",
        "الحجر",
        "النحل",
        "الإسراء",
        "الكهف",
        "مريم",
        "طه",
        "الأنبياء",
        "الحج",
        "المؤمنون",
        "النّور",
        "الفرقان",
        "الشعراء",
        "النّمل",
        "القصص",
        "العنكبوت",
        "الرّوم",
        "لقمان",
        "السجدة",
        "الأحزاب",
        "سبأ",
        "فاطر",
        "يس",
        "الصافات",
        "ص",
        "الزمر",
        "غافر",
        "فصّلت",
        "الشورى",
        "الزخرف",
        "الدّخان",
        "الجاثية",
        "الأحقاف",
        "محمد",
        "الفتح",
        "الحجرات",
        "ق",
        "الذاريات",
        "الطور",
        "النجم",
        "القمر",
        "الرحمن",
        "الواقعة",
        "الحديد",
        "المجادلة",
        "الحشر",
        "الممتحنة",
        "الصف",
        "الجمعة",
        "المنافقون",
        "التغابن",
        "الطلاق",
        "التحريم",
        "الملك",
        "القلم",
        "الحاقة",
        "المعارج",
        "نوح",
        "الجن",
        "المزّمّل",
        "المدّثر",
        "القيامة",
        "الإنسان",
        "المرسلات",
        "النبأ",
        "النازعات",
        "عبس",
        "التكوير",
        "الإنفطار",
        "المطفّفين",
        "الإنشقاق",
        "البروج",
        "الطارق",
        "الأعلى",
        "الغاشية",
        "الفجر",
        "البلد",
        "الشمس",
        "الليل",
        "الضحى",
        "الشرح",
        "التين",
        "العلق",
        "القدر",
        "البينة",
        "الزلزلة",
        "العاديات",
        "القارعة",
        "التكاثر",
        "العصر",
        "الهمزة",
        "الفيل",
        "قريش",
        "الماعون",
        "الكوثر",
        "الكافرون",
        "النصر",
        "المسد",
        "الإخلاص",
        "الفلق",
        "الناس"
    )
    val englishSuraName: List<String> = listOf(
        "Al-Fatiha", "Al-Baqarah", "Aal-E-Imran", "An-Nisa", "Al-Ma'idah", "Al-An'am",
        "Al-A'raf", "Al-Anfal", "At-Tawbah", "Yunus", "Hud", "Yusuf", "Ar-Ra'd",
        "Ibrahim", "Al-Hijr", "An-Nahl", "Al-Isra", "Al-Kahf", "Maryam", "Ta-Ha",
        "Al-Anbiya", "Al-Hajj", "Al-Mu'minun", "An-Nur", "Al-Furqan", "Ash-Shu'ara",
        "An-Naml", "Al-Qasas", "Al-Ankabut", "Ar-Rum", "Luqman", "As-Sajda",
        "Al-Ahzab", "Saba", "Fatir", "Ya-Sin", "As-Saffat", "Sad", "Az-Zumar",
        "Ghafir", "Fussilat", "Ash-Shura", "Az-Zukhruf", "Ad-Dukhan", "Al-Jathiya",
        "Al-Ahqaf", "Muhammad", "Al-Fath", "Al-Hujurat", "Qaf", "Adh-Dhariyat",
        "At-Tur", "An-Najm", "Al-Qamar", "Ar-Rahman", "Al-Waqi'a", "Al-Hadid",
        "Al-Mujadila", "Al-Hashr", "Al-Mumtahina", "As-Saff", "Al-Jumu'a",
        "Al-Munafiqun", "At-Taghabun", "At-Talaq", "At-Tahrim", "Al-Mulk",
        "Al-Qalam", "Al-Haqqa", "Al-Ma'arij", "Nuh", "Al-Jinn", "Al-Muzzammil",
        "Al-Muddaththir", "Al-Qiyama", "Al-Insan", "Al-Mursalat", "An-Naba",
        "An-Nazi'at", "Abasa", "At-Takwir", "Al-Infitar", "Al-Mutaffifin",
        "Al-Inshiqaq", "Al-Buruj", "At-Tariq", "Al-A'la", "Al-Ghashiya",
        "Al-Fajr", "Al-Balad", "Ash-Shams", "Al-Lail", "Ad-Duha", "Al-Inshirah",
        "At-Tin", "Al-Alaq", "Al-Qadr", "Al-Bayyina", "Az-Zalzalah", "Al-Adiyat",
        "Al-Qari'a", "At-Takathur", "Al-Asr", "Al-Humaza", "Al-Fil", "Quraish",
        "Al-Ma'un", "Al-Kawthar", "Al-Kafirun", "An-Nasr", "Al-Masad",
        "Al-Ikhlas", "Al-Falaq", "An-Nas"

    )
    var numberOfVerses: List<String> = listOf(
        "7 verses",
        "286 verses",
        "200 verses",
        "176 verses",
        "120 verses",
        "165 verses",
        "206 verses",
        "75 verses",
        "129 verses",
        "109 verses",
        "123 verses",
        "111 verses",
        "43 verses",
        "52 verses",
        "99 verses",
        "128 verses",
        "111 verses",
        "110 verses",
        "98 verses",
        "135 verses",
        "112 verses",
        "78 verses",
        "118 verses",
        "64 verses",
        "77 verses",
        "227 verses",
        "93 verses",
        "88 verses",
        "69 verses",
        "60 verses",
        "34 verses",
        "30 verses",
        "73 verses",
        "54 verses",
        "45 verses",
        "83 verses",
        "182 verses",
        "88 verses",
        "75 verses",
        "85 verses",
        "54 verses",
        "53 verses",
        "89 verses",
        "59 verses",
        "37 verses",
        "35 verses",
        "38 verses",
        "29 verses",
        "18 verses",
        "45 verses",
        "60 verses",
        "49 verses",
        "62 verses",
        "55 verses",
        "78 verses",
        "96 verses",
        "29 verses",
        "22 verses",
        "24 verses",
        "13 verses",
        "14 verses",
        "11 verses",
        "11 verses",
        "18 verses",
        "12 verses",
        "12 verses",
        "30 verses",
        "52 verses",
        "52 verses",
        "44 verses",
        "28 verses",
        "28 verses",
        "20 verses",
        "56 verses",
        "40 verses",
        "31 verses",
        "50 verses",
        "40 verses",
        "46 verses",
        "42 verses",
        "29 verses",
        "19 verses",
        "36 verses",
        "25 verses",
        "22 verses",
        "17 verses",
        "19 verses",
        "26 verses",
        "30 verses",
        "20 verses",
        "15 verses",
        "21 verses",
        "11 verses",
        "8 verses",
        "8 verses",
        "3 verses",
        "9 verses",
        "5 verses",
        "4 verses",
        "7 verses",
        "3 verses",
        "6 verses",
        "3 verses",
        "5 verses",
        "4 verses",
        "5 verses",
        "6 verses",
        "3 verses",
        "3 verses",
        "3 verses",
        "3 verses",
        "5 verses",
        "6 verses",
        "5 verses",
        "6 verses",
        "3 verses",
        "5 verses",
        "7 verses",
        "6 verses",
        "3 verses",
        "4 verses",
        "6 verses",
        "5 verses",
        "3 verses",
        "3 verses",
        "4 verses",
        "4 verses",
        "3 verses",
        "3 verses",
        "5 verses",
        "3 verses",
        "5 verses",
        "5 verses",
        "4 verses",
        "6 verses",
        "6 verses",
        "3 verses",
        "3 verses",
        "5 verses",
        "6 verses",
        "6 verses",
        "6 verses",
        "3 verses",
        "3 verses",
        "3 verses",
        "6 verses",
        "5 verses",
        "5 verses"
    )


    fun getChapters(): List<Chapter> {
        val chaptersList = mutableListOf<Chapter>()
        for (i in 0..113) {
            chaptersList.add(
                Chapter(
                    index = i,
                    ar_title = arabicSuraName[i],
                    en_title = englishSuraName[i],
                    versesNumber = numberOfVerses[i]
                )
            )
        }
        return chaptersList
    }
}